# fly.toml app configuration file generated for full-stack-open-pokedex-2024 on 2024-07-26T22:25:03+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-2024'
primary_region = 'arn'

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
